Repository PegaSysEng/besu-sample-networks, pull requests merged in 2019-04, with the labels that each got.

#18 add IBFT2.0 and Clique support
  .common.sh
  .env
  .gitignore
  block-explorer-light/Dockerfile
  block-explorer-light/default.nginx
  block-explorer-light/nginx.vh.conf
  docker-compose_poa.yml
  inspect-ibft2.sh
  list.sh
  pantheon_clique/.gitignore
  pantheon_clique/Dockerfile
  pantheon_clique/bootnode_start.sh
  pantheon_clique/genesis.json.template
  pantheon_clique/node_start.sh
  pantheon_ibft2/.gitignore
  pantheon_ibft2/Dockerfile
  pantheon_ibft2/bootnode_start.sh
  pantheon_ibft2/genesis.json.template
  pantheon_ibft2/node_start.sh
  remove.sh
  resume.sh
  run.sh
  stop.sh
Labels: enhancement

#23 make directory structure for node 3 privacy example
  privacy/run.sh
Labels: bug

#24 Update to pantheon 1.1.0
  .env
  privacy/.env
  privacy/README.md
  privacy/scripts/create_contract.sh
  privacy/scripts/get_receipt.sh
  privacy/scripts/get_value.sh
  privacy/scripts/set_value.sh
Labels: not ready to merge

#25 fix docker image and data folder removal
  privacy/pantheon/Dockerfile
  privacy/remove.sh
Labels: bug
